### PR TITLE
Fix array to string conversion

### LINKED ISSUE #72: Delete action: array to string conversion
Example creditmemo.yaml:
```
creditmemo:
  sales_creditmemo:
    provider:
      delete: true
```

Run: ` php bin/masquerade run --with-integrity`

Result:
```
._ _  _. _ _.    _ .__. _| _
| | |(_|_>(_||_|(/_|(_|(_|(/_
            |
                   by elgentos
                        v0.3.0
PHP Warning:  Invalid argument supplied for foreach() in /Users/tjitse/sites/masquerade/src/Elgentos/Masquerade/Console/RunCommand.php on line 129

Warning: Invalid argument supplied for foreach() in /Users/tjitse/sites/masquerade/src/Elgentos/Masquerade/Console/RunCommand.php on line 129
PHP Notice:  Array to string conversion in /Users/tjitse/sites/masquerade/src/Elgentos/Masquerade/Console/SymfonyOutput.php on line 92

Notice: Array to string conversion in /Users/tjitse/sites/masquerade/src/Elgentos/Masquerade/Console/SymfonyOutput.php on line 92
Deleting records from Array table
PHP Notice:  Array to string conversion in /Users/tjitse/sites/masquerade/src/Elgentos/Masquerade/Console/SymfonyOutput.php on line 92

Notice: Array to string conversion in /Users/tjitse/sites/masquerade/src/Elgentos/Masquerade/Console/SymfonyOutput.php on line 92
Records have been deleted from Array table

Updating [sales_creditmemo_comment]
    0/0 [----->----------------------]   0% < 1 sec Complete
```

### PR DESCRIPTION
**Pull request by Tjitse-E**
Fixes #72

### CODE REVIEW

File: src/Elgentos/Masquerade/DataProcessor/DefaultDataProcessorFactory.php [hunk 1]
```diff
@@ -24,7 +24,8 @@ public function create(
 
         $whereCondition = $tableConfiguration['where'] ?? '';
 
-        foreach ($tableConfiguration['columns'] as $column => $columnData) {
+        $columns = $tableConfiguration['columns'] ?? [];
```
Comment (Tjitse-E) [inline src/Elgentos/Masquerade/DataProcessor/DefaultDataProcessorFactory.php:27]: Fixes `PHP Notice:  Undefined index: columns in src/Elgentos/Masquerade/DataProcessor/DefaultDataProcessorFactory.php on line 27` when doing a full table delete (so without columns).

```
creditmemo:
  sales_creditmemo:
    provider:
      delete: true
```
